name: Deploy Azure OpenAI with Terraform

on:
  push:
    branches:
      - test
 
  #workflow_dispatch:  # Allows manual trigger

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Azure CLI
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az version

      # Login to Azure using OIDC (Recommended)
      - name: Azure Login
        uses: azure/login@v1
        with:
          #creds: ${{ secrets.AZURE_CREDENTIALS}}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          #client-secret: ${{ secrets.AZURE_CLIENT_SECRET_ID}}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Set Terraform Authentication Environment Variables
      - name: Set Terraform Azure Credentials
        run: |
          echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "ARM_USE_OIDC=true" >> $GITHUB_ENV

      # Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.3

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init #-backend-config="resource_group_name=tf-backend-remote-state-rg" -backend-config="storage_account_name=tfbackendstorageacct" -backend-config="container_name=remotestate"

      # Validate Terraform configuration
      - name: Terraform Validate
        run: terraform validate

      # Plan Terraform deployment
      - name: Terraform Plan
        run: terraform plan

      # Apply Terraform configuration
      - name: Terraform Apply
        run: terraform apply -auto-approve
